# Generated by Django 4.1.4 on 2022-12-18 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('canteen_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='食堂编号')),
                ('canteen_address', models.TextField(blank=True, null=True, verbose_name='食堂地址')),
                ('canteen_name', models.TextField(blank=True, null=True, verbose_name='食堂名称')),
                ('hygiene_rating', models.IntegerField(blank=True, null=True, verbose_name='卫生等级')),
            ],
            options={
                'verbose_name': '食堂',
                'verbose_name_plural': '食堂',
                'db_table': 'canteen',
                'ordering': ['canteen_id'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='菜品编号')),
                ('dish_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='菜品名称')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='菜品价格')),
                ('description', models.TextField(blank=True, null=True, verbose_name='菜品描述')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
                'db_table': 'dish',
                'ordering': ['dish_id'],
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='用户id')),
                ('password', models.CharField(max_length=10, verbose_name='用户密码')),
                ('type', models.IntegerField(verbose_name='用户类型')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'userinfo',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='CanteenManager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dish.userinfo', verbose_name='食堂管理员')),
                ('name', models.TextField(blank=True, null=True, verbose_name='管理员名称')),
            ],
            options={
                'verbose_name': '食堂管理员',
                'verbose_name_plural': '食堂管理员',
                'db_table': 'canteen_manager',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dish.userinfo', verbose_name='顾客')),
                ('name', models.TextField(blank=True, null=True, verbose_name='顾客姓名')),
            ],
            options={
                'verbose_name': '顾客',
                'verbose_name_plural': '顾客',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('dish_num', models.IntegerField(blank=True, null=True, verbose_name='菜品数量')),
                ('order_status', models.IntegerField(blank=True, null=True, verbose_name='订单状态')),
                ('address', models.TextField(blank=True, null=True, verbose_name='外送地址')),
                ('telephone', models.CharField(blank=True, max_length=10, null=True, verbose_name='联系方式')),
                ('order_time', models.DateTimeField(verbose_name='下单时间')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dish.dish', verbose_name='菜品编号')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='dish.customer', verbose_name='顾客')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='评价编号')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
                ('assessment_time', models.DateTimeField(blank=True, null=True, verbose_name='评价时间')),
                ('context', models.TextField(blank=True, null=True, verbose_name='评价内容')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dish.orders', verbose_name='订单编号')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'db_table': 'assessment',
                'ordering': ['assessment_id'],
            },
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dish.userinfo', verbose_name='商家编号')),
                ('name', models.TextField(blank=True, null=True, verbose_name='商家名称')),
                ('canteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dish.canteen', verbose_name='商家所属食堂')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
                'db_table': 'stall',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='stall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dish.stall', verbose_name='菜品商家'),
        ),
        migrations.AddField(
            model_name='canteen',
            name='canteen_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dish.canteenmanager', verbose_name='食堂管理员'),
        ),
    ]
