# Generated by Django 4.1.4 on 2022-12-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0, verbose_name='顾客状态'),
        ),
    ]
