# Generated by Django 4.1.4 on 2022-12-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_rename_name_customer_cus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dish',
            field=models.ForeignKey(blank=True, default='-1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dish.dish', verbose_name='菜品编号'),
        ),
    ]
