# Generated by Django 4.1.4 on 2022-12-25 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_alter_orders_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='stall',
            name='telephone',
            field=models.TextField(blank=True, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dish',
            field=models.ForeignKey(blank=True, default='-1', null=True, on_delete=django.db.models.deletion.CASCADE, to='dish.dish', verbose_name='菜品编号'),
        ),
    ]
