# Generated by Django 4.1.4 on 2022-12-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0005_stall_address_stall_telephone_alter_orders_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteenmanager',
            name='name',
        ),
        migrations.AddField(
            model_name='canteenmanager',
            name='telephone',
            field=models.TextField(blank=True, null=True, verbose_name='电话'),
        ),
    ]
