# Generated by Django 4.1.4 on 2022-12-25 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_remove_canteenmanager_name_canteenmanager_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dish.orders', verbose_name='订单编号'),
        ),
    ]
